title: "Belvine Lordiane Youmeni Noumou"
logo: img/bl.jpg
description: "Bachelor Student in Business Informatics | Passionate about IT Security, Data Analysis & Business Process Optimization"
show_downloads_theme: true
theme: jekyll-theme-minimal
lang: de
